### PR TITLE
Define non-anonymous module.

### PR DESCRIPTION
**Pull request by paulmillr**
amdjs/underscore is non-anonymous.

jquery is non-anonymous.

I see no reason why this should fuck build tools.

### CODE REVIEW

**Comment by paulmillr** [comment]
cc @jrburke

**Comment by jrburke** [comment]
Anonymous modules are the preferred way to develop modules, I put up some guidelines here, with some notes on why jQuery and underscore are not anonymous:

https://github.com/jrburke/requirejs/wiki/Updating-existing-libraries

So I expect that most modules will be anonymous. Maybe we can work out what build issue you saw, describe what build tools were in play, since it will be an issue with other modules.

**Comment by paulmillr** [comment]
I'm trying to move from commonjs to AMD in brunch.io 1.2 release. It's a quite popular tool to build html5 apps.

Today brunch adds a simple [commonjs definition to all files](https://github.com/brunch/twitter/blob/gh-pages/public/javascripts/vendor.js#L1-80). And it wraps all files in [`app/`](https://github.com/brunch/twitter/blob/gh-pages/app/) directory in modules like this:

``` javascript
require.define("views/user_view", function(exports, require, module) {
    // compiled file contents
    createMediator = require('chaplin/lib/create_mediator');

    module.exports = mediator = createMediator({
      createRouterProperty: true,
      createUserProperty: true
    });
});
```

and the result is concatenated to [`app.js`](https://github.com/brunch/twitter/blob/gh-pages/public/javascripts/app.js) (customizable). Because brunch users don't want to deal with ajax loading of scripts and all that boring stuff. There is also [`vendor.js`](https://github.com/brunch/twitter/blob/gh-pages/public/javascripts/vendor.js) which has concat'ed versions of libs you place in [`vendor/`](https://github.com/brunch/twitter/blob/gh-pages/vendor/scripts/). Very simple, it just works.

I've saw that many libs use amd so i've decided to give it a try. First of all, i've removed commonjs defs adding, added `require.js` to `vendor/` and changed the wrapping to `define('module', function(require, exports, module) {...})`. [It worked](https://github.com/brunch/twitter/tree/brunch-1.2) (yay, also some circular deps sucked).

The problem is — brunch wasn't adding the wrapping to `vendor` files, because usually most of vendor deps aren't commonjs-compatible. Same with amd, I guess. But if you add any ANONYMOUS dep to `vendor`, requirejs will throw an error.

So it doesn't seem to be reasonable for me to have any anonymous modules there. Libraries are libraries and they aren't meant to be developed further. In chaplin (popular app architecture on top of backbone.js) we have a `r.js` script that concats all files to one and it has non-anonymous modules too.

Any idea on how to do the stuff? Maybe I should integrate build system with `r.js` etc?

**Comment by jrburke** [comment]
AMD build tools are expected to insert a name for anonymous modules when they are built. There a different ways to do this, but r.js does this just via a regexp currently:

https://github.com/jrburke/r.js/blob/master/build/jslib/build.js#L1071

That code also pulls out [simplified commonjs require calls](http://requirejs.org/docs/whyamd.html#sugar) out into a dependency array, but that is not needed if you are targeting browsers that have workable Function.toString(). Only PS3 and older opera mobile browsers have unusable toString() methods. 

That snippet is also aware of the "namespace" build arg that r.js supports, but it is not likely to apply in your situation. 

So you can ignore the namespace and dependency array work if you like, just look at the name insertion.

So the suggestion is to scan and update anon define calls before adding them to a built file. Either that, or r.js can be used to combine the modules together, and it can do that work.

**Comment by paulmillr** [comment]
Thanks, I will try that.

**Pull request closed without merging**
