### PR TITLE
I have added the AMD wrapper to the local storage store

### PR DESCRIPTION
**Pull request by davetayls**
This file was working without the wrapper until i ran it through the optimiser and it was trying to access Backbone.sync before Backbone existed.

### CODE REVIEW

**Comment by jrburke** [comment]
We could add this, but I would not expect it to necessarily make it into any first pull request we would do for backbone to get basic AMD support into the main repo, hopefully that project will be more open to AMD support later, but in that case I would want to focus on landing and sticking the AMD support in backbone itself without adding more changes to that pull request. If that sounds OK, I'll do the merge.

**Comment by davetayls** [comment]
Sure, I expect not as well. I thought it might be helpful to people who are trying out backbone with AMD like I was. I guess you could add it as a standalone file in the amdjs/backbone fork so as not to cause potential conflicts. Anyway if you think it's useful, use as you see fit ;)

**Comment by jrburke** [comment]
Merged, but if there is a merge conflict at a later time, then I may need to back it out.

**Comment by jrburke** [comment]
I did modification, did not catch this on the merge -- the dependency should be called "backbone" to match how the backbone.js file name is normally spelled. See this commit:

https://github.com/amdjs/backbone/commit/2dba3ecfebc6fc946d52d0ef2c215fee618fac5f

**Pull request merged**
