### PR TITLE
requestjs + Backbone + jsTestDriver

### PR DESCRIPTION
**Pull request by fkowal**
Hi

I've been recently experimenting with jsTestDriver
and after writing a simple Backbone model

define('ticker/router', ['Backbone'], function (Backbone) {
    var TickerRouter = Backbone.Router.extend({...});
   return TickerRouter;
})

i wanted to test it with jsTestDriver

ticker.jstd
server: http://localhost:9876

load:
//# inject requirejs depencies used by router, model, typeView
- ../../libs/require-1.0.7.js
- ../../libs/underscore.js
- ../../libs/jquery-1.7.1.min.js
- ../../libs/backbone.js
- router.js

test:
- tests/routerTest.js

jsTestDriver fails to load Backbone

TickerRequirejsTest.testModel error (2,00 ms): Error: Mismatched anonymous define() module: function (_, $, exports) {
    root.Backbone = factory(root, exports, _, $);

it's because the AMD definition is missing a name of the module.

Please review my patch.

After applying this patch requirejs + Backbone + jsTestDriver work easy without problems with Async loading

This is my first pull request so i hope i am doing this right.

### CODE REVIEW

**Comment by unscriptable** [comment]
Hey @fkowal!

I think the problem is likely that you capitalized "Backbone".  Anonymous modules are identified by their file names.  Therefore, the loader is looking for "Backbone" and can't find it because it exists as "backbone" on the server.  

Also, your proposed fix won't work in loaders that are strict about ensuring that the name in the module matches the file fetched.  

Try this:

```
define('ticker/router', ['backbone'], function (Backbone) {
    var TickerRouter = Backbone.Router.extend({...});
    return TickerRouter;
});
```

Regards,

-- John

**Comment by fkowal** [comment]
i've changed Backbone to lowercase as you suggested
but that doesn't work still the error is 

``` js
Total 3 tests (Passed: 0; Fails: 2; Errors: 1) (8,00 ms)
  Firefox 11.0 Linux: Run 3 tests (Passed: 0; Fails: 2; Errors 1) (8,00 ms)
    TickerRequirejsTest.testModel error (2,00 ms): Error: Mismatched anonymous define() module: function (_, $, exports) {
    root.Backbone = factory(root, exports, _, $);
}
http://requirejs.org/docs/errors.html#mismatch
      makeError("mismatch","Mismatched anonymous define() module: function (_, $, exports) {\n    root.Backbone = factory(root, exports, _, $);\n}")@http://localhost:9876/test//home/mkowalski/.../js/libs/require-1.0.7.js:79
...
```

after adding 
define(**'backbone',** ['underscore'...
everything work smoothly

**Comment by unscriptable** [comment]
It sounds like you don't have a path mapped to backbone. From the looks of your code, you're using requirejs, right? 

requirejs (and most other loaders) use a paths config property to map paths to standalone modules like backbone. 

iirc, requirejs config should look like this:

requirejs.config({
  baseUrl: 'whatever/your/path/is/js',
  paths: {
    backbone: 'libs/backbone',
    underscore: 'libs/underscore'
  }
})

-- John

**Comment by fkowal** [comment]
i have this kind of config to my app when it runs in the broser and the dependencies are loaded async

but in the jsTestDriver i can't/don't want to load the dependencies asynchronously
here is a jsTestDriver.jstd config 

<pre><code>
server: http://localhost:9876

load: # here you specify what resources should be loaded (in order)
<b>//# inject requirejs depencies used by router</b>
- ../../libs/require-1.0.7.js
- ../../libs/underscore.js
- ../../libs/jquery-1.7.1.min.js
<b>- ../../libs/backbone.js</b> # here is how backbone is loaded
- router.js

test:
<b>- tests/routerTest.js</b> # test source
</code>
</pre>


_http://localhost:9876/test//home/mkowalski/myproject/js/libs/backbone.js_ this how it's being loaded
_http://localhost:9876/test/tests/routerTest.js_ - this is the request for the test
without backbone being declared as a named module everything fails

**Comment by jrburke** [comment]
It is not suggested practice to name modules in the source, that should only be done by a build tool that concatenates a bunch of modules together.

It sounds like the issue is that the jsTestDriver is just generating script tags for the file, and not having it load via requirejs. This error is expected in that case, since requirejs does not have enough info to name the module. If requirejs is used to load the module, then it can associate the correct name to it.

I would rather see this solved by using requirejs to load the file during the tests since that sounds like it would be a closer test with reality. Alternatively, change the jsTestDriver config to load require.js after loading backbone. That assumes you are not actually trying to test AMD modules that are using backbone though.

**Pull request closed without merging**
